apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-k8s-web-deployment
  labels:
    app: fastapi-k8s-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-k8s-web-deployment
  template:
    metadata:
      labels:
        app: fastapi-k8s-web-deployment
    spec:
      containers:
      - name: fastapi-k8s-web
        image: elghibaomar/customer-satisfaction-api:latest
        # imagePullPolicy: Always
        # envFrom:
        #   - secretRef:
        #       name: fastapi-web-env-prod
        env:
          - name: PORT
            value: "8007"
        ports:
        - containerPort: 8007
      # imagePullSecrets:
      #   - name: om-k8s   
      # ss


---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-k8s-web-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8007
  selector:
    app: fastapi-k8s-web-deployment